spring.application.name=ecommerce-backend

# H2 Database
spring.datasource.url=jdbc:h2:mem:ecomdb;DB_CLOSE_DELAY=-1
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true

# JPA properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Security
jwt.secret=9a67471346448e860163353986470007293540c49747573033621f3792036c61
jwt.expiration=86400000

# Server
server.port=8080
